[package]
name = "test_opencv_cross"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "0.74", default-features = false, features = ["imgproc", "highgui"]}
